1-PATHS:
  BACKGROUND_DIR: C:\ConceivableProjects\Rutine2\bg\bg2
  DETECT_DIR: null
  PROJECT_DIR: C:\ConceivableProjects\Rutine2
  VAL_DATA: C:\ConceivableProjects\Rutine2\test\v1
  WEIGHTS_DIR: C:\ConceivableProjects\Rutine2\v0.0.3\Weights\best.pt
2-PROJECT_CONFIG:
  BATCH_SIZE: 40
  BG_DATA_DISTRIBUTION: 0.8
  CLASS_NAMES:
    0: coc
  CROSS_VAL: false
  DETECT: false
  EPOCHS: 70
  EXPORT: true
  PROJECT_NAME: v0.0.4
  TRAIN: true
  TRAIN_DATA_DISTRIBUTION: 0.7
  VALIDATE_OLD_MODEL: true
3-HYPS:
  anchor_t: 2.0
  box: 0.05
  cls: 0.5
  cls_pw: 5
  copy_paste: 0.0
  degrees: 5
  fl_gamma: 0.0
  fliplr: 0.0
  flipud: 0.0
  hsv_h: 0.1
  hsv_s: 0.25
  hsv_v: 0.25
  iou_t: 0.4
  lr0: 0.001
  lrf: 0.01
  mixup: 0.0
  momentum: 0.937
  mosaic: 1.0
  obj: 0.7
  obj_pw: 5
  perspective: 0.0
  scale: 0.2
  shear: 0
  translate: 0.1
  warmup_bias_lr: 0.1
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  weight_decay: 0.0005
4-CROSS_VAL_HYPS:
  anchor_t: 3.0
  box: 0.05
  cls: 0.3
  cls_pw: 6
  copy_paste: 0.0
  degrees: 0
  fl_gamma: 0.0
  fliplr: 0.5
  flipud: 0.5
  hsv_h: 0.1
  hsv_s: 0.25
  hsv_v: 0.25
  iou_t: 0.6
  lr0: 0.001
  lrf: 0.01
  mixup: 0.0
  momentum: 0.937
  mosaic: 1.0
  obj: 0.7
  obj_pw: 6
  perspective: 0.0
  scale: 0.5
  shear: 0
  translate: 0.0
  warmup_bias_lr: 0.1
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  weight_decay: 0.0005
